# Generated by Django 5.2.16 on 2026-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3)),
                ('intra_zone_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inter_zone_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
