# Generated by Django 5.2.16 on 2026-07-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratecards', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billable_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3)),
                ('payment_type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash On Delivery')], max_length=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='CREATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('drop_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_orders', to='zones.zone')),
                ('pickup_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='zones.zone')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratecards.ratecard')),
            ],
        ),
    ]
