# Generated by Django 5.2.16 on 2026-07-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agents', to='zones.zone'),
        ),
    ]
